"""empty message

Revision ID: 3d948c69087c
Revises: 
Create Date: 2023-06-02 19:18:06.683817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d948c69087c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_details',
    sa.Column('student_id', sa.BIGINT(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('student_contact', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_details')
    # ### end Alembic commands ###
