"""empty message

Revision ID: d00865f75147
Revises: 34520bc6c352
Create Date: 2023-06-12 22:51:39.318146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00865f75147'
down_revision = '34520bc6c352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_data', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('image_id', name='images_pkey')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_conf_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_details_pkey')
    )
    # ### end Alembic commands ###
