"""empty message

Revision ID: 225aea1b0e9d
Revises: 6f6c69c6e6d6
Create Date: 2023-06-09 11:39:16.106319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225aea1b0e9d'
down_revision = 'ca780eade1df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
