"""empty message

Revision ID: 3d100b99edf5
Revises: 4f5a33919126
Create Date: 2023-06-08 14:31:10.379619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d100b99edf5'
down_revision = '4f5a33919126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('student_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_details',
    sa.Column('student_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('student_contact', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='student_details_pkey')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_conf_password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_details_pkey')
    )
    # ### end Alembic commands ###
