"""empty message

Revision ID: 6288b5c78303
Revises: 4270fc90b8dd
Create Date: 2023-06-14 23:35:47.637397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6288b5c78303'
down_revision = '4270fc90b8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('user_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_conf_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_details_pkey')
    )
    op.create_table('images',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('image_id', name='images_pkey')
    )
    # ### end Alembic commands ###
