"""empty message

Revision ID: 8936196d6900
Revises: 3d100b99edf5
Create Date: 2023-06-08 14:35:53.186013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8936196d6900'
down_revision = '3d100b99edf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
