"""empty message

Revision ID: 89eb832e6b46
Revises: a7c0bbb2dd78
Create Date: 2023-06-16 14:36:35.774741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89eb832e6b46'
down_revision = 'a7c0bbb2dd78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
