"""empty message

Revision ID: a9ede0c9f5ea
Revises: 4ee7531b146f
Create Date: 2023-06-20 00:01:48.812138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ede0c9f5ea'
down_revision = '4ee7531b146f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
