"""empty message

Revision ID: ca780eade1df
Revises: 8936196d6900
Create Date: 2023-06-08 14:53:15.156260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca780eade1df'
down_revision = '8936196d6900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_conf_password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_details_pkey')
    )
    # ### end Alembic commands ###
